Add importance sampling
FriesischScott/UncertaintyQuantification.jl pull request #124
Opened 2023-08-02 14:08 UTC by Cr0gan

Importance sampling works so far for the cantilever example (in: ./demo/IS_test.jl).
I have attached functions that evaluate the pdf for samples in a DataFrame.

Commented out are currently:
 - the sampling method from Matteo's lecture (in: src/simulations/importancesampling.jl)
 - the corresponding probability_of_failure method (in: src/reliability/probabilityoffailure.jl)
 - a function to create user-defined proposal distributions (in: src/simulations/importancesampling.jl)

2023-08-03 07:52 UTC, FriesischScott commented
English please :).

2023-08-04 07:33 UTC, FriesischScott requested changes
Sorry for this 😅 . But please remove all the proposal stuff and only implement the method based on the `Z` matrix using the design point and important direction which is currently commented out.

Put all necessary information into the `ImportanceSampling` struct. The parameter `c` can have a default of 2.

Maybe we should have an alternative implementation where `FORM` is used automatically to get the design point on the fly.

2023-08-04 07:33 UTC, FriesischScott commented on src/reliability/form.jl
> +    return pf, β, dp, α
Needs an update to the test to verify the important direction.

2023-08-04 07:33 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    proposals::Union{Vector{<:UQInput},UQInput},
The general signature for `probability_of_failure` must not change.

2023-08-04 07:33 UTC, FriesischScott commented on src/simulations/importancesampling.jl
> +# function sample(inputs::Vector{<:UQInput}, models::Union{Vector{<:UQModel},UQModel}, performance::Function, design_point_from::FORM, sim::ImportanceSampling)
I discussed with Matteo and this is the only way to do importance sampling we need to include for now. The normals centered around the design point are inefficient.

2023-10-04 12:12 UTC, FriesischScott requested changes
Looking very good apart from some very minor issues.

2023-10-04 12:12 UTC, FriesischScott commented on src/inputs/parameter.jl
> +pdf(p::Parameter, x::DataFrame) = x[!, p.name] ./ x[!, p.name]
First of all this is 1.0. And second I don't think you use it anywhere.

2023-10-04 12:12 UTC, FriesischScott commented on src/inputs/randomvariable.jl
> +var(rv::RandomVariable) = var(rv.dist)
Revert this so it doesn't show up as a change.

2023-10-04 12:12 UTC, FriesischScott commented on src/UncertaintyQuantification.jl
> +export proposaldistribution
Leftover, can be removed.

2023-10-04 12:12 UTC, FriesischScott commented on demo/reliability/cantilever.jl
> +mc = MonteCarlo(10^3)
Please revert this back for an accurate solution.

2023-10-04 12:12 UTC, FriesischScott commented on demo/reliability/cantilever.jl
> +is = ImportanceSampling(1000, β, dp, α)
Maybe use `1e4` for a comparable solution to standard MC.

2023-10-04 12:12 UTC, FriesischScott commented on test/reliability/form.jl
> +    pf, β, dp, α = probability_of_failure(df -> df.x1 .- df.x2, inputs, form)
Verify alpha is correct.

2023-10-04 12:12 UTC, FriesischScott commented on test/reliability/form.jl
> +    pf, β, dp, α = probability_of_failure(model, df -> df.y, inputs, form)
Verify alpha is correct.

2023-10-04 12:13 UTC, FriesischScott commented
After removing the `pdf` of the `Parameter` patch coverage should also be 100%.

2023-10-05 13:09 UTC, FriesischScott requested changes

2023-10-05 13:09 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
I think this should be `weights.h^2/weights.f`. This is from Matteos lecture:

```Matlab
var_pf = 1/Nsamples*(sum(failure.*normpdf(Zforced,0,1).^2./normpdf(Zforced,b,v))/Nsamples - pf^2); 
```

2023-10-05 13:09 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
This will possibly fix the issue with slightly negative variance.

2023-10-05 13:39 UTC, Cr0gan commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
In the sample method `weights.f` is `normpdf(Zforced, 0, 1)`, `weights.h` is `normpdf(Zforced, b, v)` and `weights.w` is `weights.f ./ weights.h`. Therefore `weights.w .* weights.f` should be right imo. 

Could the issue be due to some precision errors, or is the variance's absolute value too high for that?

2023-10-05 16:58 UTC, teobros commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
It should be this
`variance = ((sum(weighted_failures .* prod(normpdf(samples)) / sim.n) - pf^2) / sim.n`
but samples are in SNS for this formula

2023-10-05 17:24 UTC, Cr0gan commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
Alright, I can change that. But wouldn't that potentially lead to a negative variance as well? I think `prod(normpdf(samples))` would essentially go to zero for large amounts of samples and we would end up with `(0 - pf^2) / sim.n`.

2023-10-05 21:06 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    variance = ((sum(weighted_failures .* weights.f) / sim.n) - pf^2) / sim.n
I don't think it will. You need to essentially compute the product of the columns of the pdf values.

2023-10-18 12:58 UTC, FriesischScott approved these changes

2023-10-18 12:58 UTC, FriesischScott commented
Great stuff @Cr0gan, thanks!

2023-10-18 12:58 UTC, merged