implement qmc-randomization
FriesischScott/UncertaintyQuantification.jl pull request #143
Opened 2023-11-20 10:58 UTC by mlsuh

Using methods from QuasiMonteCarlo.jl

2023-11-28 13:26 UTC, FriesischScott requested changes

2023-11-28 13:26 UTC, FriesischScott commented on src/simulations/montecarlo.jl
> +            if !isinteger(log(base, n))
The number of samples being a power of 2 is only relevant for `SobolSampling`.

2023-11-28 13:26 UTC, FriesischScott commented on src/simulations/montecarlo.jl
> +            if !isinteger(log(base, n))
See above, not valid for `LatticeRuleSampling`.

2023-11-28 14:17 UTC, mlsuh commented on src/simulations/montecarlo.jl
> +            if !isinteger(log(base, n))
Just noticed that the warning message (l. 49) is not correct, it should be `$base` instead of `2`.

2023-12-21 15:50 UTC, FriesischScott commented
Based on the feedback from the QMC.jl devs we need to restrict lattice rules to shifting and allows scrambling only for digital nets (sobol, faure (to be added)).

Then we should contribute the `rhalton` sampling to the QMC package to allow for scrambled halton sequences. https://arxiv.org/pdf/1706.02808.pdf

2024-01-15 14:56 UTC, FriesischScott requested changes
Please sync with `master` and add test to make sure the randomization returns actual random points.

2024-01-15 14:56 UTC, FriesischScott commented on Project.toml
> +Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Needs compat entry.

2024-01-15 14:56 UTC, FriesischScott commented on src/simulations/montecarlo.jl
>      elseif sim.randomization == :digitalshift
Drop :digitalshift.

2024-01-16 11:36 UTC, FriesischScott approved these changes

2024-01-16 11:36 UTC, merged