Imprecise probabilities
FriesischScott/UncertaintyQuantification.jl pull request #146
Opened 2023-12-11 10:56 UTC by andreaperin

Implementation of imprecise probabilities with external double loop by mean of:

1. Interval struc
2. ProbabilityBox struc (no distribution-free)
3. new method for ```probability_of_failure``` function

2023-12-21 15:51 UTC, FriesischScott commented on Project.toml
> +PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
Needs a compat entry.

2023-12-21 15:52 UTC, FriesischScott commented on src/UncertaintyQuantification.jl
> +abstract type PreciseUQInput <: UQInput end
Not fully convinced by this terminology. Maybe we can find something more fitting.

2023-12-21 16:03 UTC, FriesischScott requested changes
Still missing the second algorithm ;).

Please fix the conflicts and sync with `master`.

Once the second algorithm is here I would like to see a comparison of the three global optimization toolboxes we discussed: PRIMA, BlackBoxOptim and NOMAD.

2023-12-21 16:03 UTC, FriesischScott commented on test/reliability/probabilityoffailure.jl
> +    @testset "Imprecise Probabilities Simulation" begin
Let's not use this example here but a simpler one.

2023-12-21 16:03 UTC, FriesischScott commented
@AnderGray This is still very much in progress, but if you have time and want to provide some feedback please go ahead.

2023-12-21 17:42 UTC, AnderGray reviewed
Thanks for pushing this forward! I think as a first implementation it's looking good. 

Your imprecise failure probability function looks general enough to apply to methods other than MC :)

2023-12-21 17:42 UTC, AnderGray commented on src/reliability/probabilityoffailure.jl
> +    sim::AbstractMonteCarlo,
Very cool. If you replace with `Union{AbstractMonteCarlo, AbstractSubSetSimulation}` it 'just works' with subset sim too.

2023-12-21 17:42 UTC, AnderGray commented on src/reliability/probabilityoffailure.jl
> +    sim::AbstractMonteCarlo,
I think the same applies to other simulation methods if changed to `Any`

2023-12-21 17:42 UTC, AnderGray commented on src/UncertaintyQuantification.jl
> +abstract type PreciseUQInput <: UQInput end
I agree. Also it is probably better to have a new type for the imprecise inputs rather than the precise ones? 

Since most of the package uses precise probability, and we only need to dispatch on the new imprecise stuff.

2023-12-21 17:42 UTC, AnderGray commented on src/inputs/imprecise/p-box.jl
> +    function ProbabilityBox(lb::AbstractVector{<:Real}, ub::AbstractVector{<:Real}, dist::Function, name::Symbol)
The constructor is slightly confusing ...

I think would be ideal to construct the p-box where you specify the distribution parameters as intervals, rather than making a vector of lower and upper bounds.

Perhaps something like
```Julia
mean = Interval(0, 1)
var = Interval(1, 2)
l = ProbabilityBox(Normal, [mean, std] , :l) # length
```

This is only a personal preference though.

2023-12-21 17:42 UTC, AnderGray commented on test/reliability/probabilityoffailure.jl
> +    @testset "Imprecise Probabilities Simulation" begin
It's a nice example. Should be added a demo.

2023-12-21 17:42 UTC, AnderGray commented on src/reliability/probabilityoffailure.jl
> +    return Interval(pf_lb, pf_ub, :pf)
The function is very nice. 

We should also be able to return samples of the extremal distributions right? I think this would be the two distributions which maximise and minimise the pf.

The same could apply to the COV ... however this might be trickier ... it's at least known how to return a confidence interval for an imprecise Monte Carlo simulation.

2023-12-21 18:02 UTC, andreaperin commented on src/reliability/probabilityoffailure.jl
> +    sim::AbstractMonteCarlo,
I have to create a "super type" for the abstract simulation, hopefully next week!

2023-12-22 09:33 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    sim::AbstractMonteCarlo,
Yeah, Andrea and I already discussed having a proper `AbstractSimulation` for these situations. We will then subtype `AbstractMonteCarlo` from it to separate.

2023-12-22 09:35 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    function ProbabilityBox(lb::AbstractVector{<:Real}, ub::AbstractVector{<:Real}, dist::Function, name::Symbol)
I think you are right, and I think @andreaperin wanted this as well. It's just a bit more tedious to collect the values for the upper/lower bounds but nothing major. And will be a lot more intuitive.

2023-12-22 09:36 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    function ProbabilityBox(lb::AbstractVector{<:Real}, ub::AbstractVector{<:Real}, dist::Function, name::Symbol)
Having only `UQInput` and `ImpreciseUQInput` won't work if you have both in your inputs. Unfortunately we need a supertype.

2023-12-22 10:12 UTC, FriesischScott commented on src/UncertaintyQuantification.jl
> +abstract type PreciseUQInput <: UQInput end
Sadly, I think we need both.

2023-12-22 10:13 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    return Interval(pf_lb, pf_ub, :pf)
For the demo I think we should use an example from a paper somewhwere with a reference solution.

2024-01-19 15:31 UTC, FriesischScott requested changes
See the comments for required changes. I'd also like to see the benchmarking for the three global optimization libraries. You can use `BenchmarkTools.jl`.

2024-01-19 15:31 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    dist::Function
I think I'd like to have this already in the first version. It'll be a bit annoying to write, but a lot nicer for the user.

2024-01-19 15:31 UTC, FriesischScott commented on src/inputs/imprecise/interval.jl
> +function sample(i::Interval)
Maybe we should use a different name here., as it's not really sampling.

2024-01-19 15:31 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> -function probability_of_failure(
Maybe move the functions in a file `imprecise_probabilityoffailure.jl` or something like that. Might be worth keeping the precise/imprecise stuff separately.

2024-01-19 15:31 UTC, FriesischScott commented on src/reliability/probabilityoffailure.jl
> +    return Interval(pf_lb, pf_ub, :pf)
@AnderGray is right, it would be nice to return the parameters, rvs, etc leading to the upper and lower bounds. So you could for example run other analyses after the reliability analysis for the upper and lower bounds.

2024-01-19 15:31 UTC, FriesischScott commented on test/reliability/probabilityoffailure.jl
> -@testset "Probability of Failure" begin
If the code goes into a new file, so should the tests.

2024-01-19 15:31 UTC, FriesischScott commented
@AnderGray Thoughts on the second method with inner optimization?

2024-02-22 00:09 UTC, AnderGray reviewed
Looking good. The 2nd imprecise method is very cool. Sometimes called 'random slicing', as it's based on random set theory.

What's implemented here I believe is interval Monte Carlo, and it's quite expensive. I don't know if we should tackle it in this PR, but this can be generalised to other reliability methods (FORM, importance sampling, linesampling and even SuS).

See paper by Diego Alvarez: https://doi.org/10.1016/j.ymssp.2017.07.040

The method is quite simple. You 'just' need to solve 2 imprecise reliability problems, for the upper (lower) performance functions:

<img width="797" alt="Screenshot 2024-02-21 at 23 11 57" src="https://github.com/FriesischScott/UncertaintyQuantification.jl/assets/38252522/fdb955f7-9a6f-41ec-8afa-fbd6e9abbe86">

The idea is that each `u`, a sample in SNS, has an associated upper (lower) performance function, which is found using interval prop with optimisation. So for each evaluate SNS sample from FORM/LS/SuS, you to do an interval optimisation to find the upper bound on `G`. This can be used a standard performance function in a precise reliability algorithm. This is repeated for the lower bound.

You end up with this kind of picture (physical space, copula space, SNS space)

<img width="949" alt="Screenshot 2024-02-21 at 23 54 16" src="https://github.com/FriesischScott/UncertaintyQuantification.jl/assets/38252522/e0d1bcf0-e15f-45f6-a3bc-ed96ce6fa270">

For implementation, I think it's easiest to wrap the interval performance function optimisation (like you did for Monte Carlo), and pass it to the other reliability algorithms. 

We'd also need a function to go from SNS to for p-box. This isn't too challenging under independence.

2024-02-23 00:24 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    dist::Function
I solved this by using a parametric struct. It's quite easy and intuitive.

2024-02-23 00:25 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    function ProbabilityBox(lb::AbstractVector{<:Real}, ub::AbstractVector{<:Real}, dist::Function, name::Symbol)
While I really like specifying the parameters as intervals, here it creates issues because we already have an `Interval` type with the extra `name::Symbol`.

2024-02-23 00:34 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    function ProbabilityBox(lb::AbstractVector{<:Real}, ub::AbstractVector{<:Real}, dist::Function, name::Symbol)
Mhh, I believe we could actually do it like this:
```julia
μ = Interval(0, 1, :μ)
σ = Interval(0.1, 1, :σ)
l = ProbabilityBox{Normal}([μ, σ] , :l) # length
```

Internally, we can convert the parameters to a named tuple whenever needed and pass them to the keyword constructors of the distribution. It would actually eradicate the need to have the parameters in order as well. You'd just have to use the corresponding symbols for the keywords in *Distributions.jl*. Plus it looks so clean 😄. Great suggestion.

2024-07-01 08:08 UTC, FriesischScott commented
I think we should implement proper types to dispatch on instead of dispatching on the `inputs` vector like

- `DoubleLoop(MonteCarlo(10000))`
-  `IntervalMonteCarlo(1000)`

Each  method should than check, that at least one *imprecise* input is passed and error otherwise.

2024-07-01 08:11 UTC, FriesischScott commented
On that note, we might also define the input types with the proper terminology:

- `DeterministicUQInput`
- `AleatoryUQInput`
- `EpistemicUQInput`
- `HybridUQInput`

Is this too complex? The user will usually not have to interact with these types at all. They just create their `Parameter`, `RandomVariable`, `Interval` or `ProbabilityBox` and move on. But for anyone already familiar with the terms it could be nice.

2024-07-01 16:12 UTC, FriesischScott commented
> On that note, we might also define the input types with the proper terminology:
> 
>     * `DeterministicUQInput`
> 
>     * `AleatoryUQInput`
> 
>     * `EpistemicUQInput`
> 
>     * `HybridUQInput`
> 
> 
> Is this too complex? The user will usually not have to interact with these types at all. They just create their `Parameter`, `RandomVariable`, `Interval` or `ProbabilityBox` and move on. But for anyone already familiar with the terms it could be nice.

Yeah, this is too much and unnecessary. if we dispatch on the simulation all we need is a precise and imprecise type like we have now.

2024-07-01 16:27 UTC, FriesischScott commented
> > On that note, we might also define the input types with the proper terminology:
> > ```
> > * `DeterministicUQInput`
> > 
> > * `AleatoryUQInput`
> > 
> > * `EpistemicUQInput`
> > 
> > * `HybridUQInput`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this too complex? The user will usually not have to interact with these types at all. They just create their `Parameter`, `RandomVariable`, `Interval` or `ProbabilityBox` and move on. But for anyone already familiar with the terms it could be nice.
> 
> Yeah, this is too much and unnecessary. if we dispatch on the simulation all we need is a precise and imprecise type like we have now.

@AnderGray  and I decided to just keep `UQInput` and `ImpreciseUQInput` we can filter for the *precise* inputs using `!isa`

2024-07-18 15:33 UTC, FriesischScott approved these changes

2024-07-19 13:32 UTC, AnderGray approved these changes

2024-07-19 13:43 UTC, merged