Component-wise MCMC for subset simulation
FriesischScott/UncertaintyQuantification.jl pull request #166
Opened 2024-05-08 14:15 UTC by AnderGray

This PR changes the MCMC sampler in `SubSetSimulation` from usual Metropolis-Hastings, to component-wise MH. Dimensions are accepted independently, giving a better acceptance rate in higher dimensions.

closes #165

2024-05-08 15:32 UTC, FriesischScott requested changes
Not sure what the issue with the actions is. Apart from some very minor suggestions this looks  good to me.

2024-05-08 15:32 UTC, FriesischScott commented on src/simulations/subset.jl
>  (which must be choosen without replacement at random) and modifying the acceptance rate towards the optiming
might as well fix the tyypo *optiming*

2024-05-08 16:16 UTC, AnderGray commented
Thanks for taking a look, everything should be addressed

2024-05-13 18:57 UTC, AnderGray commented
Potential bug found. Running this several times

```julia
using UncertaintyQuantification

Num_dim = 2
N_samples = 20

for j = 1:Num_dim                                                           #hide
    eval(:($(Symbol(:X,j)) = RandomVariable(Normal(0, 1), (Symbol(:X,$j))) ))#hide
end#hide

inputs = [eval(:($(Symbol(:X,i)))) for i = 1:Num_dim]                       #hide

y = Model(                                                                  #hide
    df -> sum.(eachrow(df[:, names(inputs)])),#hide
    :y,#hide
)#hide

pf_target = 10^-3

fail_limit = quantile(Normal(0, sqrt(Num_dim)), 1 - pf_target)#hide

function limitstate(df)#hide
    return fail_limit .- reduce(vcat, df.y)#hide
end#hide

simulation_method_1 = SubSetSimulation(N_samples, 0.1, 20, Uniform(-0.5, 0.5))#hide

pf_1, std_1, _ = probability_of_failure(y, limitstate, inputs, simulation_method_1)#hide
```

gives: 

```
ERROR: ArgumentError: invalid index: false of type Bool
Stacktrace:
 [1] to_index(i::Bool)
   @ Base ./indices.jl:293
 [2] to_index(A::Vector{Int64}, i::Bool)
   @ Base ./indices.jl:277
 [3] _to_indices1(A::Vector{Int64}, inds::Tuple{}, I1::Bool)
   @ Base ./indices.jl:359
 [4] to_indices
   @ ./indices.jl:354 [inlined]
 [5] to_indices
   @ ./indices.jl:350 [inlined]
 [6] getindex(::Vector{Int64}, ::Bool)
   @ Base ./abstractarray.jl:1294
 [7] nextlevelsamples(samples::DataFrames.DataFrame, performance::Vector{…}, threshold::Float64, models::Model, performancefunction::typeof(limitstate), inputs::Vector{…}, sim::SubSetSimulation)
   @ UncertaintyQuantification ~/Documents/julia/UQ_Fork_SS/Fork_2/UncertaintyQuantification.jl/src/simulations/subset.jl:300
 [8] probability_of_failure(models::Model, performancefunction::typeof(limitstate), inputs::Vector{RandomVariable}, sim::SubSetSimulation)
   @ UncertaintyQuantification ~/Documents/julia/UQ_Fork_SS/Fork_2/UncertaintyQuantification.jl/src/simulations/subset.jl:215
 [9] top-level scope
   @ REPL[35]:1
Some type information was truncated. Use `show(err)` to see complete types.

```

2024-05-14 10:36 UTC, AnderGray commented
I've also encountered issue #138

2024-05-14 11:03 UTC, FriesischScott commented
> Potential bug found. Running this several times
> 
> ```julia
> using UncertaintyQuantification
> 
> Num_dim = 2
> N_samples = 20
> 
> for j = 1:Num_dim                                                           #hide
>     eval(:($(Symbol(:X,j)) = RandomVariable(Normal(0, 1), (Symbol(:X,$j))) ))#hide
> end#hide
> 
> inputs = [eval(:($(Symbol(:X,i)))) for i = 1:Num_dim]                       #hide
> 
> y = Model(                                                                  #hide
>     df -> sum.(eachrow(df[:, names(inputs)])),#hide
>     :y,#hide
> )#hide
> 
> pf_target = 10^-3
> 
> fail_limit = quantile(Normal(0, sqrt(Num_dim)), 1 - pf_target)#hide
> 
> function limitstate(df)#hide
>     return fail_limit .- reduce(vcat, df.y)#hide
> end#hide
> 
> simulation_method_1 = SubSetSimulation(N_samples, 0.1, 20, Uniform(-0.5, 0.5))#hide
> 
> pf_1, std_1, _ = probability_of_failure(y, limitstate, inputs, simulation_method_1)#hide
> ```
> 
> gives:
> 
> ```
> ERROR: ArgumentError: invalid index: false of type Bool
> Stacktrace:
>  [1] to_index(i::Bool)
>    @ Base ./indices.jl:293
>  [2] to_index(A::Vector{Int64}, i::Bool)
>    @ Base ./indices.jl:277
>  [3] _to_indices1(A::Vector{Int64}, inds::Tuple{}, I1::Bool)
>    @ Base ./indices.jl:359
>  [4] to_indices
>    @ ./indices.jl:354 [inlined]
>  [5] to_indices
>    @ ./indices.jl:350 [inlined]
>  [6] getindex(::Vector{Int64}, ::Bool)
>    @ Base ./abstractarray.jl:1294
>  [7] nextlevelsamples(samples::DataFrames.DataFrame, performance::Vector{…}, threshold::Float64, models::Model, performancefunction::typeof(limitstate), inputs::Vector{…}, sim::SubSetSimulation)
>    @ UncertaintyQuantification ~/Documents/julia/UQ_Fork_SS/Fork_2/UncertaintyQuantification.jl/src/simulations/subset.jl:300
>  [8] probability_of_failure(models::Model, performancefunction::typeof(limitstate), inputs::Vector{RandomVariable}, sim::SubSetSimulation)
>    @ UncertaintyQuantification ~/Documents/julia/UQ_Fork_SS/Fork_2/UncertaintyQuantification.jl/src/simulations/subset.jl:215
>  [9] top-level scope
>    @ REPL[35]:1
> Some type information was truncated. Use `show(err)` to see complete types.
> ```

Can you check what the state of `reject` is when this happens? Might be an edge case where no additional rejection has to be performed. 

Could also potentially be related to the very low number of samples  with only two seeds per level.

2024-05-14 11:58 UTC, FriesischScott approved these changes
Good work!

2024-05-15 14:15 UTC, merged