Add evaluation of support for ProbabilityBoxes with Uniform
FriesischScott/UncertaintyQuantification.jl pull request #206
Opened 2024-09-25 14:52 UTC by andreaperin

closes #204

2024-09-26 08:15 UTC, FriesischScott requested changes
Good stuff, only minor comments

2024-09-26 08:15 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    if isa(T(), Uniform)
I think this can be `T` because that's already the type.

2024-09-26 08:15 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +            x -> collect(bounds(x)), vcat, filter(x -> isa(x, ImpreciseUQInput), p)
there is an `isimprecise` method you can use to filter

2024-09-26 08:15 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +        v_p = map(x -> x.value, filter(x -> isa(x, Parameter), p))
The variable names could be a bit more telling and some comments  what you are actually doing would be nice.

2024-10-02 12:13 UTC, FriesischScott requested changes
Apart from this I think it's good to go. Although I am not entirely sure if we should allow truncating uniform pboxes at all.

2024-10-02 12:13 UTC, FriesischScott commented on src/inputs/imprecise/p-box.jl
> +    if isa(T(), Uniform)
Turns out you can just do `T == Uniform`.

2024-10-02 12:17 UTC, AnderGray commented on src/inputs/imprecise/p-box.jl
> +    if isa(T(), Uniform)
I kind of agree about the truncating the uniform distribution. A truncated uniform is just another uniform. But, it might be different for a p-box?

If the application is for discretising a p-box into probability intervals, I believe there's a better way to do by directly using the upper and lower cdfs.

2024-10-02 13:55 UTC, andreaperin commented on src/inputs/imprecise/p-box.jl
> +    if isa(T(), Uniform)
truncating a Uniform distribution just return a Uniform distributon with new parameter and not a "truncated" type

2024-10-02 14:58 UTC, AnderGray approved these changes

2024-10-02 15:06 UTC, FriesischScott approved these changes

2024-10-02 17:08 UTC, merged