Add stochastic dynamics
FriesischScott/UncertaintyQuantification.jl pull request #218
Opened 2024-09-26 13:32 UTC by FriesischScott

2024-10-01 10:53 UTC, AnderGray requested changes
Thank you for this very nice PR!

I'm not really an expert on the stochastic process models / spectral representation, so I've only been able to comment on what I can understand.

I think most of the changes are quite light. The biggest one being if you could add some doc-strings in some places. I currently am unable to use these feature since I don't know what the parameter's mean.

Also, are all these stochastic processes Gaussian distributed? Or something else? What would I do if I had a covariance matrix/function and I wanted to generate samples of a gaussian random field. Could I use one of your models?

Also do you know of any examples which would have an analytical solution? I think this would make a good test for Monte Carlo and subset sim. Perhaps a simple sum of the process has known solution?

2024-10-01 10:53 UTC, AnderGray commented on src/UncertaintyQuantification.jl
> +export dft
Not sure if we should export everything. Do you think the user will be using our `dft` or `idft`? Perhaps they will which to use the FFT Julia package in their application, which could conflict with our export.

Do you need to export t `dft` and `idft` to use your features?

Feel free to disagree if this is incorrect

2024-10-01 10:53 UTC, AnderGray commented on docs/src/manual/dynamics.md
> +Stochastic dynamics studies the behaviour of buildings and systems and their changes over time when they are affected by random processes, or also called stochastic processes, such as earthquakes or
You're missing a space between the references and the text. Also present in other locations throughout the doc

2024-10-01 10:53 UTC, AnderGray commented on docs/src/manual/dynamics.md
> +If a time signal, such as an earthquake, is given and the time domain and shall be studied for their characteristics in frequency domain, the PSD estimation can be carried out. Although rigorous math
Grammar mistake in `, is given and the time domain and shall be studied ...`. Maybe you have one `and` too many?

2024-10-01 10:53 UTC, AnderGray commented on docs/src/manual/dynamics.md
> +If a time signal, such as an earthquake, is given and the time domain and shall be studied for their characteristics in frequency domain, the PSD estimation can be carried out. Although rigorous math
"...since `an` exact determination..."

2024-10-01 10:53 UTC, AnderGray commented on demo/dynamics/single-degree-of-freedom.jl
> +# samples = sample(inputs, 10)
Delete commented code

2024-10-01 10:53 UTC, AnderGray commented on src/dynamics/psd.jl
> +
Can you add some doc strings? I'm unfamiliar with these models, and do not know what the parameters's mean, or how to use these models.

2024-10-01 10:53 UTC, AnderGray commented on test/inputs/stochasticprocesses/spectralrepresentation.jl
> +    to_standard_normal_space!(srm_obj, ϕ)
Can you quickly describe what this testset is doing?

Also is `smr_obj` used / tested after the SNS transformation?

2024-10-01 11:25 UTC, marcobehrendt commented on docs/src/manual/dynamics.md
> +If a time signal, such as an earthquake, is given and the time domain and shall be studied for their characteristics in frequency domain, the PSD estimation can be carried out. Although rigorous math
Your're right, the `and` shall be `in`.

2024-10-01 11:26 UTC, marcobehrendt commented on docs/src/manual/dynamics.md
> +Stochastic dynamics studies the behaviour of buildings and systems and their changes over time when they are affected by random processes, or also called stochastic processes, such as earthquakes or
It's fixed.

2024-10-01 11:26 UTC, marcobehrendt commented on docs/src/manual/dynamics.md
> +If a time signal, such as an earthquake, is given and the time domain and shall be studied for their characteristics in frequency domain, the PSD estimation can be carried out. Although rigorous math
Fixed.

2024-10-01 11:34 UTC, marcobehrendt commented on src/UncertaintyQuantification.jl
> +export dft
We discussed this before implementation and felt that it would be better to implement our own version of dft and idft as other packages bring many dependencies. Our dft implementation will be used directly in the PSD estimation. But we can of course discuss this matter.

2024-10-01 11:38 UTC, marcobehrendt commented on test/inputs/stochasticprocesses/spectralrepresentation.jl
> +    to_standard_normal_space!(srm_obj, ϕ)
The entire testset checks the generation of stochastic processes and the re-transformation into the frequency domain with our implemented methods. A benchmark can be found in the work of Shinozuka & Deodatis (1991), on which the test set is based. 
In the current version, `srm_obj` is not tested directly after the transformation to the standard normal space and back.

2024-10-01 11:58 UTC, AnderGray commented on src/UncertaintyQuantification.jl
> +export dft
Yes, having our own implementation is a good idea. But do we need to export it, or is it only used internally? I.e. would the user ever have to call an `dft` to use your features? 

I ask this, because it can cause conflicts with other packages exporting ffts. However, after checking, I believe in the other package it's called `fft` vs our `dft`. So there wouldn't be a conflict anyway (at least with FFTW.jl).

2024-10-01 12:00 UTC, AnderGray commented on test/inputs/stochasticprocesses/spectralrepresentation.jl
> +    to_standard_normal_space!(srm_obj, ϕ)
Okey, that works 👍

2025-02-14 14:12 UTC, AnderGray approved these changes
This is awesome 🔥 I have some minor questions, but not required for merging.

- Why is it called `StochasticProcessModel`. I feel like they're more `inputs` than `Models`
- Are we able to extract stochastic process parameters, or just input them into models?
- I'm not sure how to use your `SpectralRepresentation` model. This is for modelling earthquakes? I usually work with Gaussian stochastic processes, which I define using a covariance function/kernel, or a matrix when descritised. Maybe later this could be added.
- Is it feasible to work for imprecise inputs? Marginals and/or correlation parameters?

2025-02-14 14:29 UTC, merged