Fix interval propagation for degenerate intervals
FriesischScott/UncertaintyQuantification.jl pull request #223
Opened 2024-09-30 13:50 UTC by FriesischScott

Pboxes now always return intervals even if the bounds are equal.

In the propagation, I am checking for degenerate intervals to treat them as precise values. There might be a very rare edge case here, where all intervals are degraded and none are left to propagate. We'll get to that once we encounter this issue.

2024-09-30 14:23 UTC, AnderGray requested changes
The changes look fine. However, if you uncomment the `RandomSlicing` part of the `demo/linesampling.jl`, it still errors. The error is however different this time, but indicates that there is still some instability. 

This demo is how we originally found this bug.

https://github.com/FriesischScott/UncertaintyQuantification.jl/blob/41a89ea33bfdfa7325136057a09bc8ada5bed474/demo/reliability/linesampling.jl#L66

2024-10-02 14:31 UTC, AnderGray requested changes
Other than the minor comment, I think ready to merge.

2024-10-02 14:31 UTC, AnderGray commented on src/simulations/linesampling.jl
> +        error("LineSampling does not support lines longer than 8.12.")
Seems weird that the error says `8.12`, but the criteria is `8.0`. Maybe make them the same?

2024-10-02 14:33 UTC, FriesischScott commented on src/simulations/linesampling.jl
> +        error("LineSampling does not support lines longer than 8.12.")
Oops, my bad. That was not intended.

2024-10-02 14:50 UTC, AnderGray commented
Thanks for the fix, and the changes. Looks good!

2024-10-02 14:51 UTC, merged