Add parallelisation section to docs
FriesischScott/UncertaintyQuantification.jl pull request #225
Opened 2024-10-04 14:26 UTC by FriesischScott

I added a section on parallelisation and updated the OpenSees example. I also fixed the outdated info in the hpc section and fixed a few errors/warnings here and there.

The response surface docs need more work in the future.

Closes #195,#220.

2024-10-04 14:49 UTC, AnderGray requested changes
Nice update. Some minor comments and typos I've found.

2024-10-04 14:49 UTC, AnderGray commented on docs/src/manual/parallelisation.md
> +It is important to note, that the [`ParallelModel`](@ref) requires some overhead to distribute the function calls to the workers. Therefore it performs significantly slower than the standard [`Model`
Missing an ` :

`['ExternalModel']`

2024-10-04 14:49 UTC, AnderGray commented on docs/literate/external/01-opensees.jl
> +We will be modeling the Young's modulus of the ElasticIsotropic in the OpenSees model as a  [`RandomVariable`](@ref).
Should `ElasticIsotropic ` be `isotropic elasticity`?

2024-10-04 14:49 UTC, AnderGray commented on docs/literate/external/01-opensees.jl
> +# Read output file and compute maximum (absolute) displacement
Missing full stop after `displacement.`

2024-10-04 14:49 UTC, AnderGray commented on docs/literate/external/01-opensees.jl
> +# An extractor is passed the working directory for the current sample as `base`
is passed `to` the working directory

2024-10-04 14:49 UTC, AnderGray commented on docs/literate/external/02-opensees-parallel.jl
> +@everywhere begin
Are you missing the `end` to this `begin`?

2024-10-04 14:49 UTC, AnderGray commented on docs/literate/external/02-opensees-parallel.jl
> +
It seems that this example is a pretty much replica of the non-parallel version. Is it possible to compress some of the text. I'm not sure we need to say everything again.

I think after you setup the parallel part, you can pretty much say something like `after this, the setup is the same as the serial evaluation`, and just show the code without the elaboration.

2024-10-04 16:35 UTC, FriesischScott commented on docs/literate/external/01-opensees.jl
> +We will be modeling the Young's modulus of the ElasticIsotropic in the OpenSees model as a  [`RandomVariable`](@ref).
That's the name of the material in OpenSees. But I it is missing the word *material*.

2024-10-04 16:39 UTC, FriesischScott commented on docs/literate/external/01-opensees.jl
> +# An extractor is passed the working directory for the current sample as `base`
What I mean is that the variable `base` is passed to the extractor as  the input argument. I'll reword it.

2024-10-04 16:41 UTC, FriesischScott commented on docs/literate/external/02-opensees-parallel.jl
> +@everywhere begin
No, it's just very far down.

2024-10-04 16:46 UTC, FriesischScott commented on docs/literate/external/02-opensees-parallel.jl
> +
True. I removed the comments and referred to the serial example.

2024-10-07 08:29 UTC, AnderGray approved these changes

2024-10-07 08:30 UTC, merged