design of experiments
FriesischScott/UncertaintyQuantification.jl pull request #93
Opened 2023-01-06 21:20 UTC by mlsuh

2023-01-12 12:04 UTC, FriesischScott commented
Please move the `doe.jl` into the `simulations` subfolder.

2023-05-02 08:31 UTC, mlsuh commented
FractionalFactorial and BoxBehnken are now implemented. Can be tested by (un)commenting and manipulating the respective lines of code in ...demo/metamodels/responsesurface.jl

2023-06-30 15:28 UTC, FriesischScott commented
It turns out the mapping through standard normal space etc. is not the way to go. With the design of experiments we just want to cover the input space and don't care about the exact distributions. So we are going to do the following:

For finite bounds we just scale and shift the values between the bounds of the distribution. For example, for a `Uniform(-1, 1)` the values `[0.0, 0.5, 1.0]` would become`[-1, 0.0, 1.0]`. For infinite bounds we add another property to all the designs `σ::Integer=1`. In the transformation we will use `+` or `-` `σ` times the standard deviation of the rv as the bounds.

This way, no mappings through the `cdf` are performed and there is no risk of `inf` or `nan` values.

@mlsuh Can you adapt the `sample` function to behave like this?

2023-07-12 14:40 UTC, FriesischScott requested changes
The tests don't pass.

2023-07-12 14:41 UTC, FriesischScott commented on src/simulations/doe.jl
> +function doe_samples(_::PlackettBurman, rvs::Int)
Please don't commit work in progress functions.

2023-07-12 14:42 UTC, FriesischScott requested changes

2023-07-12 14:42 UTC, FriesischScott commented on src/simulations/doe.jl
> +function sample(inputs::Array{<:UQInput}, design::AbstractDesignOfExperiments, σ::Int=1)
The sigma should be a parameter of the individual structs of the designs, not the sample function.

2023-07-13 07:38 UTC, FriesischScott commented on src/simulations/doe.jl
> +    ub = support(r.dist).ub
`ub = maximum(rv)`

2023-07-13 07:39 UTC, FriesischScott commented on src/simulations/doe.jl
> +    ub = support(r.dist).ub
`ub = isinf(ub) ? ub : std(rv) * sigma`

2023-07-13 07:40 UTC, FriesischScott commented on src/simulations/doe.jl
> +    return [ub lb]
return `[lb ub]`

2023-07-13 08:55 UTC, mlsuh commented on src/simulations/doe.jl
> +    ub = support(r.dist).ub
what about `ub = isinf(maximum(rv)) ? std(rv) * sigma : maximum(rv)`?
So, one line and no refactoring of ub but with tradeoff of extra call of `maximum(rv)`.

2023-07-14 12:20 UTC, FriesischScott approved these changes

2023-07-14 13:57 UTC, FriesischScott commented
Nice work @mlsuh!

2023-07-14 13:57 UTC, merged